-- MySQL Script generated by MySQL Workbench
-- 17 يون, 2017 EET 05:47:35 م
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema guestbook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema guestbook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `guestbook` DEFAULT CHARACTER SET utf8 ;
USE `guestbook` ;

-- -----------------------------------------------------
-- Table `guestbook`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guestbook`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guestbook`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guestbook`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guestbook`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guestbook`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NOT NULL,
  `description` TEXT NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `price` FLOAT NOT NULL,
  `available` TINYINT(1) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_product_idx` (`user_id` ASC),
  CONSTRAINT `user_product`
    FOREIGN KEY (`user_id`)
    REFERENCES `guestbook`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
